name: Push

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-20.04
    steps:
      - name: Build the hello-world Docker image
        run: |
          echo $GITHUB_PAT | docker login ghcr.io -u andreas.hansson --password-stdin
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}